# Generated by Django 4.2.7 on 2025-11-12 05:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('node_type', models.CharField(choices=[('DC', 'Distribution Center'), ('WH', 'Warehouse'), ('STORE', 'Store'), ('SUPPLIER', 'Supplier')], max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('inventory_capacity', models.IntegerField()),
                ('current_inventory', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'network_nodes',
            },
        ),
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('forecast_quantity', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('period', models.DateField()),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demands', to='agents.networknode')),
            ],
            options={
                'db_table': 'demands',
            },
        ),
        migrations.CreateModel(
            name='AgentDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_name', models.CharField(max_length=100)),
                ('decision_type', models.CharField(choices=[('REORDER', 'Reorder'), ('REDISTRIBUTE', 'Redistribute'), ('TRANSPORT', 'Transport'), ('SERVICE_ALERT', 'Service Alert'), ('FORECAST', 'Demand Forecast')], max_length=20)),
                ('urgency', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('estimated_cost', models.FloatField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('is_executed', models.BooleanField(default=False)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_decisions', to='agents.networknode')),
                ('source_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_decisions', to='agents.networknode')),
            ],
            options={
                'db_table': 'agent_decisions',
            },
        ),
    ]
